name: Docs

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build and Deploy API Docs
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Show Environment
      run: |
        xcodebuild -version
        swift --version

    - name: Install Jazzy
      run: |
        sudo gem install jazzy --no-document
        jazzy --version

    - name: Generate Docs
      run: bash Scripts/generate-docs.sh

    - name: Upload Docs Artifact
      uses: actions/upload-artifact@v4
      with:
        name: api-docs
        path: docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
        force_orphan: true

