name: Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build and Deploy API Docs
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Ruby and Jazzy
      run: |
        brew install ruby
        export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
        gem install jazzy
        
    - name: Generate Documentation
      run: |
        export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
        bash Scripts/generate-docs.sh
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        force_orphan: true
        
    - name: Upload Documentation Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation-${{ github.sha }}
        path: docs/
        retention-days: 30
